# 通用配置
spring:
  application:
    name: Yachiyo

  # 环境配置
  profiles:
    include: secret
    active: dev

# 服务器配置
server:
  port: 8080
  tomcat:
    connection-timeout: PT30S
    max-connections: 500
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 2048
  ssl:
    enabled: false
  forward-headers-strategy: framework