-- Unknown how to generate base type type

alter type vector owner to postgres;

-- Unknown how to generate base type type

alter type halfvec owner to postgres;

-- Unknown how to generate base type type

alter type sparsevec owner to postgres;

-- Unknown how to generate base type type

alter type hstore owner to postgres;

-- Unknown how to generate base type type

alter type ghstore owner to postgres;

create table users
(
    user_id  integer generated by default as identity
        primary key,
    name     varchar(15) default 'NoName'::character varying not null,
    email    varchar(40)                                     not null,
    role     varchar(10) default 'normal'::character varying not null,
    password varchar(32) default md5('123456'::text)         not null
);

comment on table users is '用户表';

comment on column users.user_id is '用户 id';

comment on column users.name is '用户名';

comment on column users.email is '邮箱地址';

comment on column users.role is '角色';

comment on column users.password is '用户密码';

alter table users
    owner to postgres;

create table llm_conversations
(
    conversation_id integer generated by default as identity
        primary key,
    user_id         integer                               not null
        constraint llm_conversations_users_user_id_fk
            references users
            on delete cascade,
    title           varchar(50) default CURRENT_TIMESTAMP not null,
    create_time     timestamp   default CURRENT_TIMESTAMP not null,
    update_time     timestamp   default CURRENT_TIMESTAMP not null
);

comment on table llm_conversations is '会话表';

comment on column llm_conversations.conversation_id is '会话 id';

comment on column llm_conversations.user_id is '用户 id';

comment on column llm_conversations.title is '标题';

comment on column llm_conversations.create_time is '创建时间';

comment on column llm_conversations.update_time is '更新时间';

alter table llm_conversations
    owner to postgres;

create index llm_conversations_conversation_id_create_time_index
    on llm_conversations (conversation_id, create_time);

create index llm_conversations_conversation_id_update_time_index
    on llm_conversations (conversation_id, update_time);

create index llm_conversations_conversation_id_user_id_index
    on llm_conversations (conversation_id, user_id);

create table posting
(
    id      integer generated by default as identity
        primary key,
    user_id integer                                                       not null
        constraint posting_users_user_id_fk
            references users
            on delete cascade,
    title   varchar(40) default '这个帖子还没有标题呢'::character varying not null,
    content text                                                          not null,
    type    varchar(18) default 'common'::character varying               not null,
    unique (id, title)
);

comment on table posting is '帖子表';

comment on column posting.id is '帖子 id';

comment on column posting.user_id is '帖子所属用户 id';

comment on column posting.title is '标题';

comment on column posting.content is '帖子内容';

comment on column posting.type is '帖子内容';

alter table posting
    owner to postgres;

create index posting_user_id_id_index
    on posting (user_id, id);

create table posting_collection
(
    user_id    integer not null
        constraint posting_collection_users_user_id_fk
            references users
            on delete cascade,
    posting_id integer not null
        constraint posting_collection_posting_id_fk
            references posting
            on delete cascade,
    primary key (user_id, posting_id)
);

comment on table posting_collection is '收藏关联';

comment on column posting_collection.user_id is '用户 id';

comment on column posting_collection.posting_id is '帖子 id';

alter table posting_collection
    owner to postgres;

create index posting_collection_user_id__index
    on posting_collection (user_id, posting_id);

create table posting_detail
(
    id         integer           not null
        primary key
        constraint posting_detail_posting_id_fk
            references posting
            on delete cascade,
    love       integer default 0 not null,
    collection integer default 0 not null,
    reading    integer default 1 not null
);

comment on table posting_detail is '帖子详情';

comment on column posting_detail.id is '帖子 id';

comment on column posting_detail.love is '喜欢数';

comment on column posting_detail.collection is '关注数';

comment on column posting_detail.reading is '阅读人数';

alter table posting_detail
    owner to postgres;

create table posting_like
(
    user_id    integer not null
        constraint posting_like_users_user_id_fk
            references users
            on delete cascade,
    posting_id integer not null
        constraint posting_like_posting_id_fk
            references posting
            on delete cascade,
    primary key (user_id, posting_id)
);

comment on table posting_like is '喜欢关联';

comment on column posting_like.user_id is '用户 id';

comment on column posting_like.posting_id is '帖子 id';

alter table posting_like
    owner to postgres;

create index posting_follow_user_id__index
    on posting_like (user_id, posting_id);

create table user_detail
(
    id           integer                                         not null
        primary key
        constraint "user-detail_users_user_id_fk"
            references users
            on delete cascade,
    name         varchar(45) default 'noname'::character varying not null,
    city         varchar(8),
    gender       varchar(2),
    birthday     date,
    introduction text
);

comment on table user_detail is '用户表详情';

comment on column user_detail.id is '用户id';

comment on column user_detail.city is '城市';

comment on column user_detail.gender is '性别';

comment on column user_detail.birthday is '生日';

comment on column user_detail.introduction is '简介';

alter table user_detail
    owner to postgres;

create table spring_ai_chat_memory
(
    conversation_id varchar(36) not null,
    content         text        not null,
    type            varchar(10) not null
        constraint spring_ai_chat_memory_type_check
            check ((type)::text = ANY
                   ((ARRAY ['USER'::character varying, 'ASSISTANT'::character varying, 'SYSTEM'::character varying, 'TOOL'::character varying])::text[])),
    timestamp       timestamp   not null
);

alter table spring_ai_chat_memory
    owner to postgres;

create index spring_ai_chat_memory_conversation_id_timestamp_idx
    on spring_ai_chat_memory (conversation_id, timestamp);

create table comment
(
    user_id    integer,
    posting_id integer not null
        constraint comment_pk
            primary key
        constraint comment_posting_id_fk
            references posting
            on delete cascade
        constraint comment_users_user_id_fk
            references users,
    content    text,
    id         integer generated by default as identity
);

comment on table comment is '评论';

comment on column comment.user_id is '用户id';

comment on column comment.posting_id is '帖子id';

comment on column comment.content is '内容';

alter table comment
    owner to postgres;

create table vector_store
(
    id        uuid default uuid_generate_v4() not null
        primary key,
    content   text,
    metadata  json,
    embedding vector(1024)
);

alter table vector_store
    owner to postgres;

create index spring_ai_vector_index
    on vector_store using hnsw (embedding vector_cosine_ops);

create table mail
(
    id          serial
        constraint mail_pk
            primary key,
    content     text,
    receiver_id integer               not null
        constraint mail_users_user_id_fk
            references users
            on delete cascade,
    sander_id   integer               not null,
    is_special  boolean default false not null
);

comment on table mail is '邮箱';

comment on column mail.receiver_id is '接收方';

comment on column mail.sander_id is '接收方';

comment on column mail.is_special is '是否是特殊邮件';

alter table mail
    owner to postgres;

create index mail_receiver_id_sander_id_index
    on mail (receiver_id, sander_id);

create table user_wallet
(
    id          integer               not null
        constraint user_wallet_pk
            primary key
        constraint user_wallet_users_user_id_fk
            references users
            on delete cascade,
    balance     numeric default 0     not null,
    version     integer,
    update_time date    default now() not null,
    create_time date    default now() not null
);

comment on table user_wallet is '用户钱包';

comment on column user_wallet.balance is '用户余额';

comment on column user_wallet.version is '乐观锁';

comment on column user_wallet.update_time is '更新时间';

comment on column user_wallet.create_time is '创建时间';

alter table user_wallet
    owner to postgres;

create table coin_log
(
    id             serial
        constraint coin_log_pk
            primary key,
    user_id        integer     default 0                         not null
        constraint coin_log_users_user_id_fk
            references users
            on delete cascade,
    change_amount  numeric     default 0                         not null,
    before_balance numeric     default 0                         not null,
    after_balance  numeric     default 0                         not null,
    business_type  varchar(50) default '签到'::character varying not null,
    create_time    date        default now()                     not null
);

comment on column coin_log.user_id is '用户 id';

comment on column coin_log.change_amount is '变更金额';

comment on column coin_log.before_balance is '之前金额';

comment on column coin_log.after_balance is '之后金额';

comment on column coin_log.create_time is '创建时间';

alter table coin_log
    owner to postgres;

create function vector_in(cstring, oid, integer) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_in(cstring, oid, integer) owner to postgres;

create function vector_out(vector) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_out(vector) owner to postgres;

create function vector_typmod_in(cstring[]) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_typmod_in(cstring[]) owner to postgres;

create function vector_recv(internal, oid, integer) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_recv(internal, oid, integer) owner to postgres;

create function vector_send(vector) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_send(vector) owner to postgres;

create function l2_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_distance(vector, vector) owner to postgres;

create function inner_product(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function inner_product(vector, vector) owner to postgres;

create function cosine_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function cosine_distance(vector, vector) owner to postgres;

create function l1_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l1_distance(vector, vector) owner to postgres;

create function vector_dims(vector) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_dims(vector) owner to postgres;

create function vector_norm(vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_norm(vector) owner to postgres;

create function l2_normalize(vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_normalize(vector) owner to postgres;

create function binary_quantize(vector) returns bit
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function binary_quantize(vector) owner to postgres;

create function subvector(vector, integer, integer) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function subvector(vector, integer, integer) owner to postgres;

create function vector_add(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_add(vector, vector) owner to postgres;

create function vector_sub(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_sub(vector, vector) owner to postgres;

create function vector_mul(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_mul(vector, vector) owner to postgres;

create function vector_concat(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_concat(vector, vector) owner to postgres;

create function vector_lt(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_lt(vector, vector) owner to postgres;

create function vector_le(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_le(vector, vector) owner to postgres;

create function vector_eq(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_eq(vector, vector) owner to postgres;

create function vector_ne(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_ne(vector, vector) owner to postgres;

create function vector_ge(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_ge(vector, vector) owner to postgres;

create function vector_gt(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_gt(vector, vector) owner to postgres;

create function vector_cmp(vector, vector) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_cmp(vector, vector) owner to postgres;

create function vector_l2_squared_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_l2_squared_distance(vector, vector) owner to postgres;

create function vector_negative_inner_product(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_negative_inner_product(vector, vector) owner to postgres;

create function vector_spherical_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_spherical_distance(vector, vector) owner to postgres;

create function vector_accum(double precision[], vector) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_accum(double precision[], vector) owner to postgres;

create function vector_avg(double precision[]) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_avg(double precision[]) owner to postgres;

create function vector_combine(double precision[], double precision[]) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_combine(double precision[], double precision[]) owner to postgres;

create function vector(vector, integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector(vector, integer, boolean) owner to postgres;

create function array_to_vector(integer[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_vector(integer[], integer, boolean) owner to postgres;

create function array_to_vector(real[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_vector(real[], integer, boolean) owner to postgres;

create function array_to_vector(double precision[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_vector(double precision[], integer, boolean) owner to postgres;

create function array_to_vector(numeric[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_vector(numeric[], integer, boolean) owner to postgres;

create function vector_to_float4(vector, integer, boolean) returns real[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_to_float4(vector, integer, boolean) owner to postgres;

create function ivfflathandler(internal) returns index_am_handler
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ivfflathandler(internal) owner to postgres;

create function hnswhandler(internal) returns index_am_handler
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hnswhandler(internal) owner to postgres;

create function ivfflat_halfvec_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ivfflat_halfvec_support(internal) owner to postgres;

create function ivfflat_bit_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ivfflat_bit_support(internal) owner to postgres;

create function hnsw_halfvec_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hnsw_halfvec_support(internal) owner to postgres;

create function hnsw_bit_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hnsw_bit_support(internal) owner to postgres;

create function hnsw_sparsevec_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hnsw_sparsevec_support(internal) owner to postgres;

create function halfvec_in(cstring, oid, integer) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_in(cstring, oid, integer) owner to postgres;

create function halfvec_out(halfvec) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_out(halfvec) owner to postgres;

create function halfvec_typmod_in(cstring[]) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_typmod_in(cstring[]) owner to postgres;

create function halfvec_recv(internal, oid, integer) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_recv(internal, oid, integer) owner to postgres;

create function halfvec_send(halfvec) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_send(halfvec) owner to postgres;

create function l2_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_distance(halfvec, halfvec) owner to postgres;

create function inner_product(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function inner_product(halfvec, halfvec) owner to postgres;

create function cosine_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function cosine_distance(halfvec, halfvec) owner to postgres;

create function l1_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l1_distance(halfvec, halfvec) owner to postgres;

create function vector_dims(halfvec) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_dims(halfvec) owner to postgres;

create function l2_norm(halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_norm(halfvec) owner to postgres;

create function l2_normalize(halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_normalize(halfvec) owner to postgres;

create function binary_quantize(halfvec) returns bit
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function binary_quantize(halfvec) owner to postgres;

create function subvector(halfvec, integer, integer) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function subvector(halfvec, integer, integer) owner to postgres;

create function halfvec_add(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_add(halfvec, halfvec) owner to postgres;

create function halfvec_sub(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_sub(halfvec, halfvec) owner to postgres;

create function halfvec_mul(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_mul(halfvec, halfvec) owner to postgres;

create function halfvec_concat(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_concat(halfvec, halfvec) owner to postgres;

create function halfvec_lt(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_lt(halfvec, halfvec) owner to postgres;

create function halfvec_le(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_le(halfvec, halfvec) owner to postgres;

create function halfvec_eq(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_eq(halfvec, halfvec) owner to postgres;

create function halfvec_ne(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_ne(halfvec, halfvec) owner to postgres;

create function halfvec_ge(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_ge(halfvec, halfvec) owner to postgres;

create function halfvec_gt(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_gt(halfvec, halfvec) owner to postgres;

create function halfvec_cmp(halfvec, halfvec) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_cmp(halfvec, halfvec) owner to postgres;

create function halfvec_l2_squared_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_l2_squared_distance(halfvec, halfvec) owner to postgres;

create function halfvec_negative_inner_product(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_negative_inner_product(halfvec, halfvec) owner to postgres;

create function halfvec_spherical_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_spherical_distance(halfvec, halfvec) owner to postgres;

create function halfvec_accum(double precision[], halfvec) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_accum(double precision[], halfvec) owner to postgres;

create function halfvec_avg(double precision[]) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_avg(double precision[]) owner to postgres;

create function halfvec_combine(double precision[], double precision[]) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_combine(double precision[], double precision[]) owner to postgres;

create function halfvec(halfvec, integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec(halfvec, integer, boolean) owner to postgres;

create function halfvec_to_vector(halfvec, integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_to_vector(halfvec, integer, boolean) owner to postgres;

create function vector_to_halfvec(vector, integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_to_halfvec(vector, integer, boolean) owner to postgres;

create function array_to_halfvec(integer[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_halfvec(integer[], integer, boolean) owner to postgres;

create function array_to_halfvec(real[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_halfvec(real[], integer, boolean) owner to postgres;

create function array_to_halfvec(double precision[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_halfvec(double precision[], integer, boolean) owner to postgres;

create function array_to_halfvec(numeric[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_halfvec(numeric[], integer, boolean) owner to postgres;

create function halfvec_to_float4(halfvec, integer, boolean) returns real[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_to_float4(halfvec, integer, boolean) owner to postgres;

create function hamming_distance(bit, bit) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hamming_distance(bit, bit) owner to postgres;

create function jaccard_distance(bit, bit) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function jaccard_distance(bit, bit) owner to postgres;

create function sparsevec_in(cstring, oid, integer) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_in(cstring, oid, integer) owner to postgres;

create function sparsevec_out(sparsevec) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_out(sparsevec) owner to postgres;

create function sparsevec_typmod_in(cstring[]) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_typmod_in(cstring[]) owner to postgres;

create function sparsevec_recv(internal, oid, integer) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_recv(internal, oid, integer) owner to postgres;

create function sparsevec_send(sparsevec) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_send(sparsevec) owner to postgres;

create function l2_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_distance(sparsevec, sparsevec) owner to postgres;

create function inner_product(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function inner_product(sparsevec, sparsevec) owner to postgres;

create function cosine_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function cosine_distance(sparsevec, sparsevec) owner to postgres;

create function l1_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l1_distance(sparsevec, sparsevec) owner to postgres;

create function l2_norm(sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_norm(sparsevec) owner to postgres;

create function l2_normalize(sparsevec) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function l2_normalize(sparsevec) owner to postgres;

create function sparsevec_lt(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_lt(sparsevec, sparsevec) owner to postgres;

create function sparsevec_le(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_le(sparsevec, sparsevec) owner to postgres;

create function sparsevec_eq(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_eq(sparsevec, sparsevec) owner to postgres;

create function sparsevec_ne(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_ne(sparsevec, sparsevec) owner to postgres;

create function sparsevec_ge(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_ge(sparsevec, sparsevec) owner to postgres;

create function sparsevec_gt(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_gt(sparsevec, sparsevec) owner to postgres;

create function sparsevec_cmp(sparsevec, sparsevec) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_cmp(sparsevec, sparsevec) owner to postgres;

create function sparsevec_l2_squared_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_l2_squared_distance(sparsevec, sparsevec) owner to postgres;

create function sparsevec_negative_inner_product(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_negative_inner_product(sparsevec, sparsevec) owner to postgres;

create function sparsevec(sparsevec, integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec(sparsevec, integer, boolean) owner to postgres;

create function vector_to_sparsevec(vector, integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function vector_to_sparsevec(vector, integer, boolean) owner to postgres;

create function sparsevec_to_vector(sparsevec, integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_to_vector(sparsevec, integer, boolean) owner to postgres;

create function halfvec_to_sparsevec(halfvec, integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function halfvec_to_sparsevec(halfvec, integer, boolean) owner to postgres;

create function sparsevec_to_halfvec(sparsevec, integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function sparsevec_to_halfvec(sparsevec, integer, boolean) owner to postgres;

create function array_to_sparsevec(integer[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_sparsevec(integer[], integer, boolean) owner to postgres;

create function array_to_sparsevec(real[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_sparsevec(real[], integer, boolean) owner to postgres;

create function array_to_sparsevec(double precision[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_sparsevec(double precision[], integer, boolean) owner to postgres;

create function array_to_sparsevec(numeric[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function array_to_sparsevec(numeric[], integer, boolean) owner to postgres;

create function hstore_in(cstring) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_in(cstring) owner to postgres;

create function hstore_out(hstore) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_out(hstore) owner to postgres;

create function hstore_recv(internal) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_recv(internal) owner to postgres;

create function hstore_send(hstore) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_send(hstore) owner to postgres;

create function hstore_version_diag(hstore) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_version_diag(hstore) owner to postgres;

create function fetchval(hstore, text) returns text
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function fetchval(hstore, text) owner to postgres;

create function slice_array(hstore, text[]) returns text[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function slice_array(hstore, text[]) owner to postgres;

create function slice(hstore, text[]) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function slice(hstore, text[]) owner to postgres;

create function isexists(hstore, text) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function isexists(hstore, text) owner to postgres;

create function exist(hstore, text) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function exist(hstore, text) owner to postgres;

create function exists_any(hstore, text[]) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function exists_any(hstore, text[]) owner to postgres;

create function exists_all(hstore, text[]) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function exists_all(hstore, text[]) owner to postgres;

create function isdefined(hstore, text) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function isdefined(hstore, text) owner to postgres;

create function defined(hstore, text) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function defined(hstore, text) owner to postgres;

create function delete(hstore, text) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function delete(hstore, text) owner to postgres;

create function delete(hstore, text[]) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function delete(hstore, text[]) owner to postgres;

create function delete(hstore, hstore) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function delete(hstore, hstore) owner to postgres;

create function hs_concat(hstore, hstore) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hs_concat(hstore, hstore) owner to postgres;

create function hs_contains(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hs_contains(hstore, hstore) owner to postgres;

create function hs_contained(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hs_contained(hstore, hstore) owner to postgres;

create function tconvert(text, text) returns hstore
    immutable
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function tconvert(text, text) owner to postgres;

create function hstore(text, text) returns hstore
    immutable
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore(text, text) owner to postgres;

create function hstore(text[], text[]) returns hstore
    immutable
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore(text[], text[]) owner to postgres;

create function hstore(text[]) returns hstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore(text[]) owner to postgres;

create function hstore_to_json(hstore) returns json
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_to_json(hstore) owner to postgres;

create function hstore_to_json_loose(hstore) returns json
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_to_json_loose(hstore) owner to postgres;

create function hstore_to_jsonb(hstore) returns jsonb
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_to_jsonb(hstore) owner to postgres;

create function hstore_to_jsonb_loose(hstore) returns jsonb
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_to_jsonb_loose(hstore) owner to postgres;

create function hstore(record) returns hstore
    immutable
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore(record) owner to postgres;

create function hstore_to_array(hstore) returns text[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_to_array(hstore) owner to postgres;

create function hstore_to_matrix(hstore) returns text[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_to_matrix(hstore) owner to postgres;

create function akeys(hstore) returns text[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function akeys(hstore) owner to postgres;

create function avals(hstore) returns text[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function avals(hstore) owner to postgres;

create function skeys(hstore) returns setof text
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function skeys(hstore) owner to postgres;

create function svals(hstore) returns setof text
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function svals(hstore) owner to postgres;

create function each(hs hstore, out key text, out value text) returns setof record
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function each(hstore, out text, out text) owner to postgres;

create function populate_record(anyelement, hstore) returns anyelement
    immutable
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function populate_record(anyelement, hstore) owner to postgres;

create function hstore_eq(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_eq(hstore, hstore) owner to postgres;

create function hstore_ne(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_ne(hstore, hstore) owner to postgres;

create function hstore_gt(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_gt(hstore, hstore) owner to postgres;

create function hstore_ge(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_ge(hstore, hstore) owner to postgres;

create function hstore_lt(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_lt(hstore, hstore) owner to postgres;

create function hstore_le(hstore, hstore) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_le(hstore, hstore) owner to postgres;

create function hstore_cmp(hstore, hstore) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_cmp(hstore, hstore) owner to postgres;

create function hstore_hash(hstore) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_hash(hstore) owner to postgres;

create function ghstore_in(cstring) returns ghstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_in(cstring) owner to postgres;

create function ghstore_out(ghstore) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_out(ghstore) owner to postgres;

create function ghstore_compress(internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_compress(internal) owner to postgres;

create function ghstore_decompress(internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_decompress(internal) owner to postgres;

create function ghstore_penalty(internal, internal, internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_penalty(internal, internal, internal) owner to postgres;

create function ghstore_picksplit(internal, internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_picksplit(internal, internal) owner to postgres;

create function ghstore_union(internal, internal) returns ghstore
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_union(internal, internal) owner to postgres;

create function ghstore_same(ghstore, ghstore, internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_same(ghstore, ghstore, internal) owner to postgres;

create function ghstore_consistent(internal, hstore, smallint, oid, internal) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_consistent(internal, hstore, smallint, oid, internal) owner to postgres;

create function gin_extract_hstore(hstore, internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function gin_extract_hstore(hstore, internal) owner to postgres;

create function gin_extract_hstore_query(hstore, internal, smallint, internal, internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function gin_extract_hstore_query(hstore, internal, smallint, internal, internal) owner to postgres;

create function gin_consistent_hstore(internal, smallint, hstore, integer, internal, internal) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function gin_consistent_hstore(internal, smallint, hstore, integer, internal, internal) owner to postgres;

create function hstore_hash_extended(hstore, bigint) returns bigint
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_hash_extended(hstore, bigint) owner to postgres;

create function ghstore_options(internal) returns void
    immutable
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function ghstore_options(internal) owner to postgres;

create function hstore_subscript_handler(internal) returns internal
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function hstore_subscript_handler(internal) owner to postgres;

create function uuid_nil() returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_nil() owner to postgres;

create function uuid_ns_dns() returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_ns_dns() owner to postgres;

create function uuid_ns_url() returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_ns_url() owner to postgres;

create function uuid_ns_oid() returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_ns_oid() owner to postgres;

create function uuid_ns_x500() returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_ns_x500() owner to postgres;

create function uuid_generate_v1() returns uuid
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_generate_v1() owner to postgres;

create function uuid_generate_v1mc() returns uuid
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_generate_v1mc() owner to postgres;

create function uuid_generate_v3(namespace uuid, name text) returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_generate_v3(uuid, text) owner to postgres;

create function uuid_generate_v4() returns uuid
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_generate_v4() owner to postgres;

create function uuid_generate_v5(namespace uuid, name text) returns uuid
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
    end;
$$;

alter function uuid_generate_v5(uuid, text) owner to postgres;

create operator <-> (procedure = l2_distance, leftarg = vector, rightarg = vector, commutator = <->);

alter operator <->(vector, vector) owner to postgres;

create operator <#> (procedure = vector_negative_inner_product, leftarg = vector, rightarg = vector, commutator = <#>);

alter operator <#>(vector, vector) owner to postgres;

create operator <=> (procedure = cosine_distance, leftarg = vector, rightarg = vector, commutator = <=>);

alter operator <=>(vector, vector) owner to postgres;

create operator <+> (procedure = l1_distance, leftarg = vector, rightarg = vector, commutator = <+>);

alter operator <+>(vector, vector) owner to postgres;

create operator + (procedure = vector_add, leftarg = vector, rightarg = vector, commutator = +);

alter operator +(vector, vector) owner to postgres;

create operator - (procedure = vector_sub, leftarg = vector, rightarg = vector);

alter operator -(vector, vector) owner to postgres;

create operator * (procedure = vector_mul, leftarg = vector, rightarg = vector, commutator = *);

alter operator *(vector, vector) owner to postgres;

create operator || (procedure = vector_concat, leftarg = vector, rightarg = vector);

alter operator ||(vector, vector) owner to postgres;

create operator <-> (procedure = l2_distance, leftarg = halfvec, rightarg = halfvec, commutator = <->);

alter operator <->(halfvec, halfvec) owner to postgres;

create operator <#> (procedure = halfvec_negative_inner_product, leftarg = halfvec, rightarg = halfvec, commutator = <#>);

alter operator <#>(halfvec, halfvec) owner to postgres;

create operator <=> (procedure = cosine_distance, leftarg = halfvec, rightarg = halfvec, commutator = <=>);

alter operator <=>(halfvec, halfvec) owner to postgres;

create operator <+> (procedure = l1_distance, leftarg = halfvec, rightarg = halfvec, commutator = <+>);

alter operator <+>(halfvec, halfvec) owner to postgres;

create operator + (procedure = halfvec_add, leftarg = halfvec, rightarg = halfvec, commutator = +);

alter operator +(halfvec, halfvec) owner to postgres;

create operator - (procedure = halfvec_sub, leftarg = halfvec, rightarg = halfvec);

alter operator -(halfvec, halfvec) owner to postgres;

create operator * (procedure = halfvec_mul, leftarg = halfvec, rightarg = halfvec, commutator = *);

alter operator *(halfvec, halfvec) owner to postgres;

create operator || (procedure = halfvec_concat, leftarg = halfvec, rightarg = halfvec);

alter operator ||(halfvec, halfvec) owner to postgres;

create operator <~> (procedure = hamming_distance, leftarg = bit, rightarg = bit, commutator = <~>);

alter operator <~>(bit, bit) owner to postgres;

create operator <%> (procedure = jaccard_distance, leftarg = bit, rightarg = bit, commutator = <%>);

alter operator <%>(bit, bit) owner to postgres;

create operator <-> (procedure = l2_distance, leftarg = sparsevec, rightarg = sparsevec, commutator = <->);

alter operator <->(sparsevec, sparsevec) owner to postgres;

create operator <#> (procedure = sparsevec_negative_inner_product, leftarg = sparsevec, rightarg = sparsevec, commutator = <#>);

alter operator <#>(sparsevec, sparsevec) owner to postgres;

create operator <=> (procedure = cosine_distance, leftarg = sparsevec, rightarg = sparsevec, commutator = <=>);

alter operator <=>(sparsevec, sparsevec) owner to postgres;

create operator <+> (procedure = l1_distance, leftarg = sparsevec, rightarg = sparsevec, commutator = <+>);

alter operator <+>(sparsevec, sparsevec) owner to postgres;

create operator -> (procedure = fetchval, leftarg = hstore, rightarg = text);

alter operator ->(hstore, text) owner to postgres;

create operator -> (procedure = slice_array, leftarg = hstore, rightarg = text[]);

alter operator ->(hstore, text[]) owner to postgres;

create operator ? (procedure = exist, leftarg = hstore, rightarg = text, join = matchingjoinsel, restrict = matchingsel);

alter operator ?(hstore, text) owner to postgres;

create operator ?| (procedure = exists_any, leftarg = hstore, rightarg = text[], join = matchingjoinsel, restrict = matchingsel);

alter operator ?|(hstore, text[]) owner to postgres;

create operator ?& (procedure = exists_all, leftarg = hstore, rightarg = text[], join = matchingjoinsel, restrict = matchingsel);

alter operator ?&(hstore, text[]) owner to postgres;

create operator - (procedure = delete, leftarg = hstore, rightarg = text);

alter operator -(hstore, text) owner to postgres;

create operator - (procedure = delete, leftarg = hstore, rightarg = text[]);

alter operator -(hstore, text[]) owner to postgres;

create operator - (procedure = delete, leftarg = hstore, rightarg = hstore);

alter operator -(hstore, hstore) owner to postgres;

create operator || (procedure = hs_concat, leftarg = hstore, rightarg = hstore);

alter operator ||(hstore, hstore) owner to postgres;

create operator %% (procedure = hstore_to_array, rightarg = hstore);

alter operator %%(none, hstore) owner to postgres;

create operator %# (procedure = hstore_to_matrix, rightarg = hstore);

alter operator %#(none, hstore) owner to postgres;

create operator #= (procedure = populate_record, leftarg = anyelement, rightarg = hstore);

alter operator #=(anyelement, hstore) owner to postgres;

create aggregate avg(vector) (
    sfunc = vector_accum,
    stype = double precision[],
    finalfunc = vector_avg,
    combinefunc = vector_combine,
    initcond = '{0}',
    parallel = safe
    );

alter aggregate avg(vector) owner to postgres;

create aggregate sum(vector) (
    sfunc = vector_add,
    stype = vector,
    combinefunc = vector_add,
    parallel = safe
    );

alter aggregate sum(vector) owner to postgres;

create aggregate avg(halfvec) (
    sfunc = halfvec_accum,
    stype = double precision[],
    finalfunc = halfvec_avg,
    combinefunc = halfvec_combine,
    initcond = '{0}',
    parallel = safe
    );

alter aggregate avg(halfvec) owner to postgres;

create aggregate sum(halfvec) (
    sfunc = halfvec_add,
    stype = halfvec,
    combinefunc = halfvec_add,
    parallel = safe
    );

alter aggregate sum(halfvec) owner to postgres;

create operator family vector_ops using btree;

alter operator family vector_ops using btree add
    operator 5 >(vector, vector),
    operator 4 >=(vector, vector),
    operator 1 <(vector, vector),
    operator 2 <=(vector, vector),
    operator 3 =(vector, vector),
    function 1(vector, vector) vector_cmp(vector, vector);

alter operator family vector_ops using btree owner to postgres;

create operator class vector_ops default for type vector using btree as
    operator 5 >(vector, vector),
    operator 1 <(vector, vector),
    operator 2 <=(vector, vector),
    operator 3 =(vector, vector),
    operator 4 >=(vector, vector),
    function 1(vector, vector) vector_cmp(vector, vector);

alter operator class vector_ops using btree owner to postgres;

create operator family vector_l2_ops using ivfflat;

alter operator family vector_l2_ops using ivfflat add
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector),
    function 3(vector, vector) l2_distance(vector, vector);

alter operator family vector_l2_ops using ivfflat owner to postgres;

create operator class vector_l2_ops default for type vector using ivfflat as
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector),
    function 3(vector, vector) l2_distance(vector, vector);

alter operator class vector_l2_ops using ivfflat owner to postgres;

create operator family vector_ip_ops using ivfflat;

alter operator family vector_ip_ops using ivfflat add
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 4(vector, vector) vector_norm(vector),
    function 3(vector, vector) vector_spherical_distance(vector, vector);

alter operator family vector_ip_ops using ivfflat owner to postgres;

create operator class vector_ip_ops for type vector using ivfflat as
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 4(vector, vector) vector_norm(vector),
    function 3(vector, vector) vector_spherical_distance(vector, vector);

alter operator class vector_ip_ops using ivfflat owner to postgres;

create operator family vector_cosine_ops using ivfflat;

alter operator family vector_cosine_ops using ivfflat add
    operator 1 <=>(vector, vector) for order by float_ops,
    function 3(vector, vector) vector_spherical_distance(vector, vector),
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 4(vector, vector) vector_norm(vector),
    function 2(vector, vector) vector_norm(vector);

alter operator family vector_cosine_ops using ivfflat owner to postgres;

create operator class vector_cosine_ops for type vector using ivfflat as
    operator 1 <=>(vector, vector) for order by float_ops,
    function 2(vector, vector) vector_norm(vector),
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 3(vector, vector) vector_spherical_distance(vector, vector),
    function 4(vector, vector) vector_norm(vector);

alter operator class vector_cosine_ops using ivfflat owner to postgres;

create operator family vector_l2_ops using hnsw;

alter operator family vector_l2_ops using hnsw add
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector);

alter operator family vector_l2_ops using hnsw owner to postgres;

create operator class vector_l2_ops for type vector using hnsw as
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector);

alter operator class vector_l2_ops using hnsw owner to postgres;

create operator family vector_ip_ops using hnsw;

alter operator family vector_ip_ops using hnsw add
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector);

alter operator family vector_ip_ops using hnsw owner to postgres;

create operator class vector_ip_ops for type vector using hnsw as
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector);

alter operator class vector_ip_ops using hnsw owner to postgres;

create operator family vector_cosine_ops using hnsw;

alter operator family vector_cosine_ops using hnsw add
    operator 1 <=>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 2(vector, vector) vector_norm(vector);

alter operator family vector_cosine_ops using hnsw owner to postgres;

create operator class vector_cosine_ops for type vector using hnsw as
    operator 1 <=>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 2(vector, vector) vector_norm(vector);

alter operator class vector_cosine_ops using hnsw owner to postgres;

create operator family vector_l1_ops using hnsw;

alter operator family vector_l1_ops using hnsw add
    operator 1 <+>(vector, vector) for order by float_ops,
    function 1(vector, vector) l1_distance(vector, vector);

alter operator family vector_l1_ops using hnsw owner to postgres;

create operator class vector_l1_ops for type vector using hnsw as
    operator 1 <+>(vector, vector) for order by float_ops,
    function 1(vector, vector) l1_distance(vector, vector);

alter operator class vector_l1_ops using hnsw owner to postgres;

create operator family halfvec_ops using btree;

alter operator family halfvec_ops using btree add
    operator 5 >(halfvec, halfvec),
    operator 4 >=(halfvec, halfvec),
    operator 3 =(halfvec, halfvec),
    operator 2 <=(halfvec, halfvec),
    operator 1 <(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_cmp(halfvec, halfvec);

alter operator family halfvec_ops using btree owner to postgres;

create operator class halfvec_ops default for type halfvec using btree as
    operator 1 <(halfvec, halfvec),
    operator 3 =(halfvec, halfvec),
    operator 5 >(halfvec, halfvec),
    operator 2 <=(halfvec, halfvec),
    operator 4 >=(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_cmp(halfvec, halfvec);

alter operator class halfvec_ops using btree owner to postgres;

create operator family halfvec_l2_ops using ivfflat;

alter operator family halfvec_l2_ops using ivfflat add
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec),
    function 3(halfvec, halfvec) l2_distance(halfvec, halfvec);

alter operator family halfvec_l2_ops using ivfflat owner to postgres;

create operator class halfvec_l2_ops for type halfvec using ivfflat as
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) l2_distance(halfvec, halfvec),
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec);

alter operator class halfvec_l2_ops using ivfflat owner to postgres;

create operator family halfvec_ip_ops using ivfflat;

alter operator family halfvec_ip_ops using ivfflat add
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 4(halfvec, halfvec) l2_norm(halfvec);

alter operator family halfvec_ip_ops using ivfflat owner to postgres;

create operator class halfvec_ip_ops for type halfvec using ivfflat as
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 4(halfvec, halfvec) l2_norm(halfvec),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal);

alter operator class halfvec_ip_ops using ivfflat owner to postgres;

create operator family halfvec_cosine_ops using ivfflat;

alter operator family halfvec_cosine_ops using ivfflat add
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 2(halfvec, halfvec) l2_norm(halfvec),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 4(halfvec, halfvec) l2_norm(halfvec),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec);

alter operator family halfvec_cosine_ops using ivfflat owner to postgres;

create operator class halfvec_cosine_ops for type halfvec using ivfflat as
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 2(halfvec, halfvec) l2_norm(halfvec),
    function 4(halfvec, halfvec) l2_norm(halfvec);

alter operator class halfvec_cosine_ops using ivfflat owner to postgres;

create operator family halfvec_l2_ops using hnsw;

alter operator family halfvec_l2_ops using hnsw add
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec);

alter operator family halfvec_l2_ops using hnsw owner to postgres;

create operator class halfvec_l2_ops for type halfvec using hnsw as
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator class halfvec_l2_ops using hnsw owner to postgres;

create operator family halfvec_ip_ops using hnsw;

alter operator family halfvec_ip_ops using hnsw add
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec);

alter operator family halfvec_ip_ops using hnsw owner to postgres;

create operator class halfvec_ip_ops for type halfvec using hnsw as
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec);

alter operator class halfvec_ip_ops using hnsw owner to postgres;

create operator family halfvec_cosine_ops using hnsw;

alter operator family halfvec_cosine_ops using hnsw add
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 2(halfvec, halfvec) l2_norm(halfvec),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator family halfvec_cosine_ops using hnsw owner to postgres;

create operator class halfvec_cosine_ops for type halfvec using hnsw as
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 2(halfvec, halfvec) l2_norm(halfvec),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec);

alter operator class halfvec_cosine_ops using hnsw owner to postgres;

create operator family halfvec_l1_ops using hnsw;

alter operator family halfvec_l1_ops using hnsw add
    operator 1 <+>(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) l1_distance(halfvec, halfvec);

alter operator family halfvec_l1_ops using hnsw owner to postgres;

create operator class halfvec_l1_ops for type halfvec using hnsw as
    operator 1 <+>(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) l1_distance(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator class halfvec_l1_ops using hnsw owner to postgres;

create operator family bit_hamming_ops using ivfflat;

alter operator family bit_hamming_ops using ivfflat add
    operator 1 <~>(bit, bit) for order by float_ops,
    function 3(bit, bit) hamming_distance(bit, bit),
    function 1(bit, bit) hamming_distance(bit, bit),
    function 5(bit, bit) ivfflat_bit_support(internal);

alter operator family bit_hamming_ops using ivfflat owner to postgres;

create operator class bit_hamming_ops for type bit using ivfflat as
    operator 1 <~>(bit, bit) for order by float_ops,
    function 1(bit, bit) hamming_distance(bit, bit),
    function 5(bit, bit) ivfflat_bit_support(internal),
    function 3(bit, bit) hamming_distance(bit, bit);

alter operator class bit_hamming_ops using ivfflat owner to postgres;

create operator family bit_hamming_ops using hnsw;

alter operator family bit_hamming_ops using hnsw add
    operator 1 <~>(bit, bit) for order by float_ops,
    function 3(bit, bit) hnsw_bit_support(internal),
    function 1(bit, bit) hamming_distance(bit, bit);

alter operator family bit_hamming_ops using hnsw owner to postgres;

create operator class bit_hamming_ops for type bit using hnsw as
    operator 1 <~>(bit, bit) for order by float_ops,
    function 1(bit, bit) hamming_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator class bit_hamming_ops using hnsw owner to postgres;

create operator family bit_jaccard_ops using hnsw;

alter operator family bit_jaccard_ops using hnsw add
    operator 1 <%>(bit, bit) for order by float_ops,
    function 1(bit, bit) jaccard_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator family bit_jaccard_ops using hnsw owner to postgres;

create operator class bit_jaccard_ops for type bit using hnsw as
    operator 1 <%>(bit, bit) for order by float_ops,
    function 1(bit, bit) jaccard_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator class bit_jaccard_ops using hnsw owner to postgres;

create operator family sparsevec_ops using btree;

alter operator family sparsevec_ops using btree add
    operator 4 >=(sparsevec, sparsevec),
    operator 2 <=(sparsevec, sparsevec),
    operator 3 =(sparsevec, sparsevec),
    operator 1 <(sparsevec, sparsevec),
    operator 5 >(sparsevec, sparsevec),
    function 1(sparsevec, sparsevec) sparsevec_cmp(sparsevec, sparsevec);

alter operator family sparsevec_ops using btree owner to postgres;

create operator class sparsevec_ops default for type sparsevec using btree as
    operator 1 <(sparsevec, sparsevec),
    operator 2 <=(sparsevec, sparsevec),
    operator 3 =(sparsevec, sparsevec),
    operator 4 >=(sparsevec, sparsevec),
    operator 5 >(sparsevec, sparsevec),
    function 1(sparsevec, sparsevec) sparsevec_cmp(sparsevec, sparsevec);

alter operator class sparsevec_ops using btree owner to postgres;

create operator family sparsevec_l2_ops using hnsw;

alter operator family sparsevec_l2_ops using hnsw add
    operator 1 <->(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) sparsevec_l2_squared_distance(sparsevec, sparsevec);

alter operator family sparsevec_l2_ops using hnsw owner to postgres;

create operator class sparsevec_l2_ops for type sparsevec using hnsw as
    operator 1 <->(sparsevec, sparsevec) for order by float_ops,
    function 1(sparsevec, sparsevec) sparsevec_l2_squared_distance(sparsevec, sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator class sparsevec_l2_ops using hnsw owner to postgres;

create operator family sparsevec_ip_ops using hnsw;

alter operator family sparsevec_ip_ops using hnsw add
    operator 1 <#>(sparsevec, sparsevec) for order by float_ops,
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator family sparsevec_ip_ops using hnsw owner to postgres;

create operator class sparsevec_ip_ops for type sparsevec using hnsw as
    operator 1 <#>(sparsevec, sparsevec) for order by float_ops,
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator class sparsevec_ip_ops using hnsw owner to postgres;

create operator family sparsevec_cosine_ops using hnsw;

alter operator family sparsevec_cosine_ops using hnsw add
    operator 1 <=>(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 2(sparsevec, sparsevec) l2_norm(sparsevec),
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec);

alter operator family sparsevec_cosine_ops using hnsw owner to postgres;

create operator class sparsevec_cosine_ops for type sparsevec using hnsw as
    operator 1 <=>(sparsevec, sparsevec) for order by float_ops,
    function 2(sparsevec, sparsevec) l2_norm(sparsevec),
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator class sparsevec_cosine_ops using hnsw owner to postgres;

create operator family sparsevec_l1_ops using hnsw;

alter operator family sparsevec_l1_ops using hnsw add
    operator 1 <+>(sparsevec, sparsevec) for order by float_ops,
    function 1(sparsevec, sparsevec) l1_distance(sparsevec, sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator family sparsevec_l1_ops using hnsw owner to postgres;

create operator class sparsevec_l1_ops for type sparsevec using hnsw as
    operator 1 <+>(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) l1_distance(sparsevec, sparsevec);

alter operator class sparsevec_l1_ops using hnsw owner to postgres;

create operator family btree_hstore_ops using btree;

alter operator family btree_hstore_ops using btree add
    operator 4 #>=#(hstore, hstore),
    operator 2 #<=#(hstore, hstore),
    operator 3 =(hstore, hstore),
    operator 1 #<#(hstore, hstore),
    operator 5 #>#(hstore, hstore),
    function 1(hstore, hstore) hstore_cmp(hstore, hstore);

alter operator family btree_hstore_ops using btree owner to postgres;

create operator class btree_hstore_ops default for type hstore using btree as
    operator 3 =(hstore, hstore),
    operator 5 #>#(hstore, hstore),
    operator 4 #>=#(hstore, hstore),
    operator 2 #<=#(hstore, hstore),
    operator 1 #<#(hstore, hstore),
    function 1(hstore, hstore) hstore_cmp(hstore, hstore);

alter operator class btree_hstore_ops using btree owner to postgres;

create operator family hash_hstore_ops using hash;

alter operator family hash_hstore_ops using hash add
    operator 1 =(hstore, hstore),
    function 2(hstore, hstore) hstore_hash_extended(hstore, bigint),
    function 1(hstore, hstore) hstore_hash(hstore);

alter operator family hash_hstore_ops using hash owner to postgres;

create operator class hash_hstore_ops default for type hstore using hash as
    operator 1 =(hstore, hstore),
    function 1(hstore, hstore) hstore_hash(hstore);

alter operator class hash_hstore_ops using hash owner to postgres;

create operator family gist_hstore_ops using gist;

alter operator family gist_hstore_ops using gist add
    operator 7 @>(hstore, hstore),
    operator 9 ?(hstore, text),
    operator 10 ?|(hstore, text[]),
    operator 11 ?&(hstore, text[]),
    function 6(hstore, hstore) ghstore_picksplit(internal, internal),
    function 1(hstore, hstore) ghstore_consistent(internal, hstore, smallint, oid, internal),
    function 2(hstore, hstore) ghstore_union(internal, internal),
    function 3(hstore, hstore) ghstore_compress(internal),
    function 4(hstore, hstore) ghstore_decompress(internal),
    function 5(hstore, hstore) ghstore_penalty(internal, internal, internal),
    function 7(hstore, hstore) ghstore_same(ghstore, ghstore, internal),
    function 10(hstore, hstore) ghstore_options(internal);

alter operator family gist_hstore_ops using gist owner to postgres;

create operator class gist_hstore_ops default for type hstore using gist as storage ghstore function 6(hstore, hstore) ghstore_picksplit(internal, internal),
	function 5(hstore, hstore) ghstore_penalty(internal, internal, internal),
	function 7(hstore, hstore) ghstore_same(ghstore, ghstore, internal),
	function 1(hstore, hstore) ghstore_consistent(internal, hstore, smallint, oid, internal),
	function 2(hstore, hstore) ghstore_union(internal, internal);

alter operator class gist_hstore_ops using gist owner to postgres;

create operator family gin_hstore_ops using gin;

alter operator family gin_hstore_ops using gin add
    operator 7 @>(hstore, hstore),
    operator 9 ?(hstore, text),
    operator 10 ?|(hstore, text[]),
    operator 11 ?&(hstore, text[]),
    function 4(hstore, hstore) gin_consistent_hstore(internal, smallint, hstore, integer, internal, internal),
    function 1(hstore, hstore) bttextcmp(text,text),
    function 3(hstore, hstore) gin_extract_hstore_query(hstore, internal, smallint, internal, internal),
    function 2(hstore, hstore) gin_extract_hstore(hstore, internal);

alter operator family gin_hstore_ops using gin owner to postgres;

create operator class gin_hstore_ops default for type hstore using gin as storage text function 3(hstore, hstore) gin_extract_hstore_query(hstore, internal, smallint, internal, internal),
	function 2(hstore, hstore) gin_extract_hstore(hstore, internal);

alter operator class gin_hstore_ops using gin owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = halfvec_ne, leftarg = halfvec, rightarg = halfvec, commutator = <>, negator = =, join = eqjoinsel, restrict = eqsel);

alter operator <>(halfvec, halfvec) owner to postgres;

create operator = (procedure = halfvec_eq, leftarg = halfvec, rightarg = halfvec, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel);

alter operator =(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = hstore_ne, leftarg = hstore, rightarg = hstore, commutator = <>, negator = =, join = neqjoinsel, restrict = neqsel);

alter operator <>(hstore, hstore) owner to postgres;

create operator = (procedure = hstore_eq, leftarg = hstore, rightarg = hstore, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel, hashes, merges);

alter operator =(hstore, hstore) owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = sparsevec_ne, leftarg = sparsevec, rightarg = sparsevec, commutator = <>, negator = =, join = eqjoinsel, restrict = eqsel);

alter operator <>(sparsevec, sparsevec) owner to postgres;

create operator = (procedure = sparsevec_eq, leftarg = sparsevec, rightarg = sparsevec, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel);

alter operator =(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = vector_ne, leftarg = vector, rightarg = vector, commutator = <>, negator = =, join = eqjoinsel, restrict = eqsel);

alter operator <>(vector, vector) owner to postgres;

create operator = (procedure = vector_eq, leftarg = vector, rightarg = vector, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel);

alter operator =(vector, vector) owner to postgres;

-- Cyclic dependencies found

create operator <@ (procedure = hs_contained, leftarg = hstore, rightarg = hstore, commutator = @>, join = matchingjoinsel, restrict = matchingsel);

alter operator <@(hstore, hstore) owner to postgres;

create operator @> (procedure = hs_contains, leftarg = hstore, rightarg = hstore, commutator = <@, join = matchingjoinsel, restrict = matchingsel);

alter operator @>(hstore, hstore) owner to postgres;

-- Cyclic dependencies found

create operator #<# (procedure = hstore_lt, leftarg = hstore, rightarg = hstore, commutator = #>#, negator = #>=#, join = scalarltjoinsel, restrict = scalarltsel);

alter operator #<#(hstore, hstore) owner to postgres;

-- Cyclic dependencies found

create operator #># (procedure = hstore_gt, leftarg = hstore, rightarg = hstore, commutator = #<#, negator = #<=#, join = scalargtjoinsel, restrict = scalargtsel);

alter operator #>#(hstore, hstore) owner to postgres;

-- Cyclic dependencies found

create operator #<=# (procedure = hstore_le, leftarg = hstore, rightarg = hstore, commutator = #>=#, negator = #>#, join = scalarlejoinsel, restrict = scalarlesel);

alter operator #<=#(hstore, hstore) owner to postgres;

create operator #>=# (procedure = hstore_ge, leftarg = hstore, rightarg = hstore, commutator = #<=#, negator = #<#, join = scalargejoinsel, restrict = scalargesel);

alter operator #>=#(hstore, hstore) owner to postgres;

-- Cyclic dependencies found

create operator < (procedure = halfvec_lt, leftarg = halfvec, rightarg = halfvec, commutator = >, negator = >=, join = scalarltjoinsel, restrict = scalarltsel);

alter operator <(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator > (procedure = halfvec_gt, leftarg = halfvec, rightarg = halfvec, commutator = <, negator = <=, join = scalargtjoinsel, restrict = scalargtsel);

alter operator >(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator <= (procedure = halfvec_le, leftarg = halfvec, rightarg = halfvec, commutator = >=, negator = >, join = scalarlejoinsel, restrict = scalarlesel);

alter operator <=(halfvec, halfvec) owner to postgres;

create operator >= (procedure = halfvec_ge, leftarg = halfvec, rightarg = halfvec, commutator = <=, negator = <, join = scalargejoinsel, restrict = scalargesel);

alter operator >=(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator < (procedure = sparsevec_lt, leftarg = sparsevec, rightarg = sparsevec, commutator = >, negator = >=, join = scalarltjoinsel, restrict = scalarltsel);

alter operator <(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator > (procedure = sparsevec_gt, leftarg = sparsevec, rightarg = sparsevec, commutator = <, negator = <=, join = scalargtjoinsel, restrict = scalargtsel);

alter operator >(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator <= (procedure = sparsevec_le, leftarg = sparsevec, rightarg = sparsevec, commutator = >=, negator = >, join = scalarlejoinsel, restrict = scalarlesel);

alter operator <=(sparsevec, sparsevec) owner to postgres;

create operator >= (procedure = sparsevec_ge, leftarg = sparsevec, rightarg = sparsevec, commutator = <=, negator = <, join = scalargejoinsel, restrict = scalargesel);

alter operator >=(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator < (procedure = vector_lt, leftarg = vector, rightarg = vector, commutator = >, negator = >=, join = scalarltjoinsel, restrict = scalarltsel);

alter operator <(vector, vector) owner to postgres;

-- Cyclic dependencies found

create operator > (procedure = vector_gt, leftarg = vector, rightarg = vector, commutator = <, negator = <=, join = scalargtjoinsel, restrict = scalargtsel);

alter operator >(vector, vector) owner to postgres;

-- Cyclic dependencies found

create operator <= (procedure = vector_le, leftarg = vector, rightarg = vector, commutator = >=, negator = >, join = scalarlejoinsel, restrict = scalarlesel);

alter operator <=(vector, vector) owner to postgres;

create operator >= (procedure = vector_ge, leftarg = vector, rightarg = vector, commutator = <=, negator = <, join = scalargejoinsel, restrict = scalargesel);

alter operator >=(vector, vector) owner to postgres;

